name: Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: downcase REPO
        run: |
          echo "IMAGE_NAME=registry.chelos.pw/teyvatbytes/$(echo ${{ github.event.repository.name }} | awk '{print tolower($0)}')" >>${GITHUB_ENV}

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: registry.chelos.pw
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          target: production
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{env.IMAGE_NAME}}:${{ github.ref_name }}-${{ github.sha }}-${{ github.run_number }}
